## CICD --> Build & Push docker image to ECR + Update image tag in DEV environment
name: Merge CI

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'deployment/**'
    branches:
      - master

jobs:
  install-yarn:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: install yarn
        run: |
          sudo npm cache clean -f
          sudo npm install -g n
          sudo n stable
          sudo npm install -g yarn

  build-client-prod:
    needs: [ install-yarn ]
    strategy:
      matrix: 
        env-mapping: 
        - { env: nvq2, bucket: ovp-kalt-static-content }
        - { env: nvp1, bucket: static-content }
    uses: kaltura/ovp-pipelines/.github/workflows/build_FE.yml@3.1.0
    with:
      environment: ${{ matrix.env-mapping.env }}
      working-dir: "."
      bucket-name-suffix: ${{ matrix.env-mapping.bucket }}
      bucket-name-key: "content/static/player-scripts"
      install-command: "npm install"
      build-command: "yarn run build"
  
